# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FlKL0QO9kBuLpgvkE6dhZl1dAKO3fzoyqM89PtUiSztx47WLx0n/a9F3ztadNOfPDmfP4/WYsRUjWxLQROMNSDRZBHDzguvVB/zkIBEj231bU4zCpk8EkTGOhqCnsQtCBz3xD8WzKGhSgP4G5skQtRo5BkS0WVhDumJzxyP4VL/n1qxE/RMY55+ISTPUkUbzebjLcg3dlaFupO1wYWXqZutP7W5eDH5/Lg0Wq+g5x5QQcbHkPqB1TrCD7VXKAUDFBuqvaKTy4NUno+OjyPaJrOKEANDXi3gahlLd+b7TOIEHR5ryKhWsG2Ek38j1WqStZXoYWSLIB3iUDef4chsPx5yYrTvsbv3+qJwRkpS3zs5l/VxdQcx1oOGANVChWZ7Bo9rmArvQo92KfcCMz2X9H9lj5LZp2OT2fNRjbWc8Hr2N1lYSCQG5We5nnWmk9oo+coXKsJeI0FMmSq38XQx4PbU7fwPoZPjx6BKCgYJFjlj5FGJyg2/NLTTPhE5tnGm6/4eb99e5kGsXz5KQntfNhScI6M+SDqP4S6HQaz45RPZ/Roe7qqTeaQan1GbDyla4001l6IK/xQLdPCCfRvzIHJPMYPY9EDdaEPns5BatyGTDtD4l6c3P8DVOg6Z2VQymTSX+RmiX6XJkNImMHauW/wPAHJKPr7lZRnOt22OWouA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
