travis:
  secure:
    BINSTAR_TOKEN: QWmBcrEAwSHOAqdyb/xWgwjpQSeo7ig/YoBCVHUXdzqqcjm5f6afHJsiX7NFWx4Y4ttcAcWup9+XCg5qvvlf1Ku/K2T03tGLIiZOpSYH4hZcJyGRqSYpGVnOIFtHhnT+Qziho0OZ2My6wGAetDiawlG2T42XipNLOFGxqxMzRgyGSHbD9Bj9Hvu2QFBtazwmsEcQ63R0t/ge7LmFTMItCpKGIm9rH8yKl8KymieiZDUSWu21g/Ln8JpOZy3V53dqZnTsWrr7T2QCDRznE/HhCaHa5R2iC+MlC4g4Cn40ZhtkaFqDD1BDmd580e9d4CbiOsm13J3DMa0FEnuZNyMG+bIxEGLdkJ5kb4eMTRK37FUiIMDf8pfvCWQv5U73MpeZkFfQa0fXP5yq/cfK1JRu94CkYus7QCGoEuCVBXpTQPXc04Z5NGmh/r/7dicGcLX8g3pu9NsiuLA/284y0yfyDQGWWezzHnD2vXqTTUkTTy64yas73yljjVwAPMlJeRBSqJz0igWMeCOhJKHFvJ5qjAsqURQM+m6w4JtbP3racvtUYhmPfNn6wNGoQ8VOY/FsZV4kWB54D2EngKHVtgRSVmZ6Tu+lGC8Y8kOUUcpBXzraV8pXBg2Xh3ehe1ErdsXhSGpMiyoHW1LZmnY01ueS13y8Qtor8LBFWpigk4wShkM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
