travis:
  secure:
    BINSTAR_TOKEN: DLmDAMUJ+PrCQ8oLiZTve4YQtWLGa/DsP2eS9ijIlG+E2B2pxaaYdwGGme5Oa0cJooOfAJfdhxnyZ5yhMa2LbpxrL8F9lxs4z/jQtuHNd6Jxi76A9jAtQX7CFLDtxNVGdM12Lg9loqAsEsnqXi/MVDQuKxBrkl+u7uzOXXsKrI8viHfuTCp/sD2OmdDx0n8h9HkSmoJvp5n7kfXz4a3Yu3+Pnmdewf4gbn9nIadiojkftaDbmhkgcuHJ+5j5jJyWLDC6umy8MCguK6GI73OAcVFsmTw+MrNH9C8vh1MDJ8HSO7CyXpCqlPcNvmbFlb8/qcqV1TLjZijnWPtW1MGcS4ASiJsDjNJz4YABL2KrgA78YweYaC/foIy/O6Y1vT58kxN/mwDfeMRIYraWf/HfhCp6nYFxFAvn63NqluuRt+r0SzizqLnv5425M4OWoDrZ/AKEXg9W0l0i8Hn7hjjVTw8iWs8EVqVDGA3zg4X6VY+22DrkWbq0c4/NHC2NVNyIA263aa2OXiVd6H3mDChYszftk8tDjUiy68bB0Xjh2oi43sOsIBGiPJOVyWqdFG1jHevFANwnsTXPSBN6G3wr3rghvvMmTH7e8a7UGw7g8S44Tozrgki9AW4UzVpPQurJTAZ28gfrwymX6QiVXHPuoKlbAvKHNJxBWPWH6WaDWl0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
