appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: TruBTXfOfQEOe3qVPH2M3u5jhGCRCX9ly+FjAdJQf+PFbpWaqogL9llKcMrdcU4/WbuEwtFuAIuHOeOkaXYHNOlFoQ98RaQeNtr/ZU2pmNLfjrAdF83UWG8Ml5EOy2jVvMRrdeAwclWtWvEKB30uZYpKM8nA9OMWWKh9Xp0BDSPD6fZzhl4hPKt1X6QfxR1DnD9n+dAl9wNs98jRrIO8uGYm6T7ESdmmQ6hyfLZ6igfVv61ObeSKXkv0Pd4Qvh7Acl4g/7lQ2Q1jSERELQVZnpKKK/BCb6GlW9XI0Fpg0CDzt3Lixyuy+nUGUU++kaNPLwf4UVxK7NM6Kkfm3ozxwv8JeKD+Cve1CvEcMKSH7EhVaG2O+pJg8lzH/SWRztIOvGJLoRv4wmun6aejLiOwOoL9VkmojF7zpyLwVK0OLNoIZpq35Gdov6apRjL3ZE5UFFf3HNs4E05kYjUpnOO7xyVRTjyMKQdlXacxZf4+pPNBojUmyIzX8pvmXhPDMbZmoD17l4ryGPIc+wsa0epqGepaM61qjC/gXouFGNWxS9SUp/LnHbilLEJCUAEJQ7dtrtp0L9Y0wGXP624xUU45sn5ebGnXJyx6OImqOKappfcg7XCK1qtQMfAbl/C6kTdG1y0o3JA59NPduCfS0zbEE0omMM1bxRULnmSUlpN0Jxg=}
