travis:
  secure:
    BINSTAR_TOKEN: FlKL0QO9kBuLpgvkE6dhZl1dAKO3fzoyqM89PtUiSztx47WLx0n/a9F3ztadNOfPDmfP4/WYsRUjWxLQROMNSDRZBHDzguvVB/zkIBEj231bU4zCpk8EkTGOhqCnsQtCBz3xD8WzKGhSgP4G5skQtRo5BkS0WVhDumJzxyP4VL/n1qxE/RMY55+ISTPUkUbzebjLcg3dlaFupO1wYWXqZutP7W5eDH5/Lg0Wq+g5x5QQcbHkPqB1TrCD7VXKAUDFBuqvaKTy4NUno+OjyPaJrOKEANDXi3gahlLd+b7TOIEHR5ryKhWsG2Ek38j1WqStZXoYWSLIB3iUDef4chsPx5yYrTvsbv3+qJwRkpS3zs5l/VxdQcx1oOGANVChWZ7Bo9rmArvQo92KfcCMz2X9H9lj5LZp2OT2fNRjbWc8Hr2N1lYSCQG5We5nnWmk9oo+coXKsJeI0FMmSq38XQx4PbU7fwPoZPjx6BKCgYJFjlj5FGJyg2/NLTTPhE5tnGm6/4eb99e5kGsXz5KQntfNhScI6M+SDqP4S6HQaz45RPZ/Roe7qqTeaQan1GbDyla4001l6IK/xQLdPCCfRvzIHJPMYPY9EDdaEPns5BatyGTDtD4l6c3P8DVOg6Z2VQymTSX+RmiX6XJkNImMHauW/wPAHJKPr7lZRnOt22OWouA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
